service: valence-aws-javascript-takehome

plugins:
  - serverless-dotenv-plugin

frameworkVersion: ">=1.1.0 <2.0.0"

provider:
  name: aws
  runtime: nodejs8.10

functions:
  forecast:
    handler: handler.forecast
    events:
      - http:
          path: ping
method: get
